### PR TITLE
responseText check that doesn't break in IE9

### PR DESCRIPTION
**Pull request by jerryorr**

### CODE REVIEW

**Comment by mattsgarlata** [comment]
+1, but I'll let Nathan take a look at it before merging.

**Comment by mattsgarlata** [comment]
Nathan, what are your thoughts on this?  I need this fix for IE9 compatability

**Comment by nathanbowser** [comment]
I told Jerry on slack that he could go ahead and merge it.

**Comment by mattsgarlata** [comment]
Cool.  Merged.

**Pull request merged**
